Repository kube-burner/kube-burner-ocp, pull requests merged in 2024-09, with the labels that each got.

#105 pods-per-node and iterations shouln't have default values higher than 0
  custom-workload.go
Labels: bug, ok-to-test

#100 Fix golangci-lint precommit hook
  .golangci.yml
  .pre-commit-config.yaml
  cluster_health.go
  egressip.go
  index.go
Labels: bug, ok-to-test

#101 Code changes to capture node bootup times for self-managed cluster
  README.md
  cmd/ocp.go
  go.mod
  go.sum
  pkg/workers_scale/autoscaler.go
  pkg/workers_scale/base.go
  pkg/workers_scale/constants.go
  pkg/workers_scale/machines.go
  pkg/workers_scale/metrics.go
  pkg/workers_scale/types.go
  pkg/workers_scale/utils.go
  workers-scale.go
Labels: ok-to-test

#106 New udn-density-l3-pods workload
  README.md
  cmd/config/udn-density-l3-pods/deployment-client.yml
  cmd/config/udn-density-l3-pods/deployment-server.yml
  cmd/config/udn-density-l3-pods/udn-density-l3-pods.yml
  cmd/config/udn-density-l3-pods/udn.yml
  cmd/ocp.go
  udn-density-l3-pods.go
Labels: enhancement, ok-to-test

#107 Adding rosa classic to workers scale workload
  pkg/workerscale/autoscaler.go
  pkg/workerscale/base.go
  pkg/workerscale/constants.go
  pkg/workerscale/machines.go
  pkg/workerscale/metrics.go
  pkg/workerscale/rosa.go
  pkg/workerscale/types.go
  pkg/workerscale/utils.go
  workers-scale.go
Labels: ok-to-test

#112 Remove useless flags
  cmd/config/udn-density-l3-pods/udn-density-l3-pods.yml
  udn-density-l3-pods.go
Labels: ok-to-test
