Repository kube-burner/kube-burner-ocp, pull requests merged in 2024-11, with the labels that each got.

#140 Adding l2 udn workload
  cmd/config/udn-density-l2-pods/deployment-client.yml
  cmd/config/udn-density-l2-pods/deployment-server.yml
  cmd/config/udn-density-l2-pods/udn-density-l2-pods.yml
  cmd/config/udn-density-l2-pods/udn.yml
  cmd/ocp.go
  udn-density-pods.go
Labels: ok-to-test

#125 [PERFSCALE-3052] Add new core RDS workload
  README.md
  cmd/config/rds-core/bgpadvertisement.yml
  cmd/config/rds-core/bgppeer.yml
  cmd/config/rds-core/configmap.yml
  cmd/config/rds-core/deployment-client.yml
  cmd/config/rds-core/deployment-dpdk.yml
  cmd/config/rds-core/deployment-server.yml
  cmd/config/rds-core/ipaddresspool.yml
  cmd/config/rds-core/np-allow-from-clients.yml
  cmd/config/rds-core/np-allow-from-ingress.yml
  cmd/config/rds-core/np-deny-all.yml
  cmd/config/rds-core/rds-core.yml
  cmd/config/rds-core/route.yml
  cmd/config/rds-core/secret.yml
  cmd/config/rds-core/service-lb.yml
  cmd/config/rds-core/service.yml
  cmd/config/rds-core/sriov-network.yml
  cmd/ocp.go
  rds-core.go
Labels: enhancement, ok-to-test

#141 Decrease readinessProbe period
  cmd/config/cluster-density-v2/deployment-client.yml
Labels: enhancement, ok-to-test

#145 Disable health check on index subcmd
  cmd/ocp.go
Labels: ok-to-test

#146 Disable file logging on extract
  cmd/ocp.go
Labels: bug, ok-to-test

#143 Add cgroup RSS queries
  cmd/config/metrics-aggregated.yml
  cmd/config/metrics-egressip.yml
  cmd/config/metrics-report.yml
  cmd/config/metrics.yml
Labels: ok-to-test

#144 Remove etcd leader change metric
  cmd/config/metrics-aggregated.yml
  cmd/config/metrics-egressip.yml
  cmd/config/metrics.yml
Labels: enhancement, ok-to-test

#148 CRD test case
  cmd/config/crd-scale/crd-scale.yml
  test/test-ocp.bats
Labels: enhancement, ok-to-test

#137 Use embedded metrics-profiles in index subcmd
  cmd/ocp.go
  index.go
Labels: ok-to-test

#150 Adding whereabouts workload
  cmd/config/whereabouts/ipam-fast.yml
  cmd/config/whereabouts/ipam.yml
  cmd/config/whereabouts/pod.yml
  cmd/config/whereabouts/whereabouts.yml
  cmd/ocp.go
  whereabouts.go
Labels: ok-to-test

#151 Bump kube-burner core version
  cmd/ocp.go
  go.mod
  go.sum
Labels: dependencies, ok-to-test

#152 [PERFSCALE-3594] Refactor udn-density-pods
  cmd/config/udn-density-l3-pods/deployment-client.yml
  cmd/config/udn-density-l3-pods/deployment-server.yml
  cmd/config/udn-density-l3-pods/udn-density-l3-pods.yml
  cmd/config/udn-density-pods/deployment-client.yml
  cmd/config/udn-density-pods/deployment-server.yml
  cmd/config/udn-density-pods/udn-density-pods.yml
  cmd/config/udn-density-pods/udn_l2.yml
  cmd/config/udn-density-pods/udn_l3.yml
  udn-density-pods.go
Labels: ok-to-test

#117 network policy workload
  README.md
  cmd/config/network-policy/egress-np.yml
  cmd/config/network-policy/ingress-np.yml
  cmd/config/network-policy/network-policy.yml
  cmd/config/network-policy/np-allow-from-proxy.yml
  cmd/config/network-policy/np-deny-all.yml
  cmd/config/network-policy/pod.yml
  cmd/ocp.go
  network-policy.go
  networkpolicy.go
Labels: ok-to-test

#156 Add explicit alert for ClusterOperatorDown
  cmd/config/alerts.yml
Labels: ok-to-test
