Repository kube-burner/kube-burner-ocp, pull requests merged in 2024-02, with the labels that each got.

#6 Bump kube-burner version
  go.mod
  go.sum
Labels: enhancement

#14 Fixing cluster-density network policies
  cmd/config/cluster-density-v2/np-allow-from-clients.yml
  cmd/config/cluster-density-v2/np-allow-from-ingress.yml
Labels: bug, enhancement

#11 Node 20 GHA
  .github/workflows/builders.yml
  .github/workflows/docs.yml
  .github/workflows/gorelease.yml
  .github/workflows/test-ocp.yml
Labels: CI

#13 Service latency flag
  cluster-density.go
  cmd/config/cluster-density-v2/cluster-density-v2.yml
  cmd/config/node-density-cni/node-density-cni.yml
  node-density-cni.go
  test/test-ocp.bats
Labels: enhancement

#12 Skip PersistentPreRun on version subcmd
  cmd/ocp.go
Labels: bug

#8 Don't configure Indexer in workloads.Config
  cmd/ocp.go
  go.mod
  go.sum
Labels: bug

#20 Bump kube-burner dependency
  go.mod
  go.sum
  index.go
Labels: enhancement

#21 Health checkocp
  cluster-density.go
  cluster_health.go
  cmd/ocp.go
  common.go
  test/test-ocp.bats
Labels: enhancement
