Repository kube-burner/kube-burner-ocp, pull requests merged in 2025-05, with the labels that each got.

#231 Move Stackrox metrics to a separate profile
  cmd/config/metrics-report-stackrox.yml
  cmd/config/metrics-report.yml
Labels: help wanted, ok-to-test

#234 Move ralatency to pkg and implement only for Linux
  README.md
  cmd/ocp.go
  go.mod
  go.sum
  pkg/measurements/routeadvertisement-latency_linux.go
  pkg/measurements/routeadvertisement-latency_unspecified.go
  udn-bgp.go
Labels: ok-to-test

#237 Run opensearch as part of running the CI locally
  test/helpers.bash
  test/test-ocp.bats
Labels: ok-to-test

#236 GH Action - add a build matrix workflow
  .github/workflows/build-matrix.yml
  .github/workflows/ci-tests.yml
Labels: ok-to-test

#219 Consolidate node-density workloads into a single file
  cmd/config/node-density-heavy/node-density-heavy.yml
  cmd/ocp.go
  node-density-cni.go
  node-density-heavy.go
  node-density.go
Labels: ok-to-test

#218 Remove clusterrole and clusterrolebinding
  cmd/config/clusterrole.yml
  cmd/config/clusterrolebinding.yml
Labels: ok-to-test

#217 Remove web-burner tests
  test/test-ocp.bats
Labels: ok-to-test

#241 Bump kube-burner version
  go.mod
  go.sum
Labels: dependencies, ok-to-test

#243 Fix logic to sort tags based on creation date
  .github/workflows/docs.yml
Labels: ok-to-test

#245 Flag to enable/disable file logging
  cmd/ocp.go
Labels: enhancement, ok-to-test

#246 Replace `kube_deployment_labels` and `kube_replicaset_labels` with `k…
  cmd/config/metrics-aggregated.yml
  cmd/config/metrics-egressip.yml
  cmd/config/metrics.yml
Labels: ok-to-test

#240 OLMv1 workload
  README.md
  cluster_health.go
  cmd/config/olm/clustercatalog.yml
  cmd/config/olm/olm.yml
  cmd/ocp.go
  olmv1.go
  test/test-ocp.bats
Labels: ok-to-test

#248 Bump to v1.16.0
  go.mod
  go.sum
Labels: ok-to-test

#251 Fix RDS core typo
  cmd/config/rds-core/bgpadvertisement.yml
Labels: ok-to-test

#254 Preload vm images
  cmd/config/virt-density/virt-density.yml
  cmd/config/virt-udn-density/virt-udn-density.yml
Labels: bug, ok-to-test

#252 Add test for DV Cloning
  README.md
  cmd/config/dv-clone/dv-clone.yml
  cmd/config/dv-clone/templates/baseImageDataSource.yml
  cmd/config/dv-clone/templates/baseImageDataVolume.yml
  cmd/config/dv-clone/templates/baseImageDataVolumeSnapshot.yml
  cmd/config/dv-clone/templates/cloneImageDataVolume.yml
  cmd/ocp.go
  dv-clone.go
  test/test-ocp.bats
Labels: ok-to-test
