Repository kube-burner/kube-burner-ocp, pull requests merged in 2025-01, with the labels that each got.

#167 kube-burner v1.12.1
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  cmd/ocp.go
  go.mod
  go.sum
  index.go
Labels: ok-to-test

#158 Image registry failure should be fatal
  cluster-density.go
  cluster_health.go
Labels: ok-to-test

#169 Makefile - add the configuration files to the binary sources
  Makefile
Labels: ok-to-test

#149 add connectivity check via svc in readiness probe
  cmd/config/udn-density-pods/deployment-client.yml
  cmd/config/udn-density-pods/service.yml
  cmd/config/udn-density-pods/udn-density-pods.yml
Labels: ok-to-test

#154 [PERFSCALE-3598] virt-density
  cmd/config/virt-density/Containerfile
  cmd/config/virt-density/virt-density.yml
  cmd/config/virt-density/vm.yml
  cmd/ocp.go
  virt-density.go
Labels: enhancement, ok-to-test

#171 Split udn creation and other objects, parameterize job pause
  cmd/config/udn-density-pods/udn-density-pods.yml
  udn-density-pods.go
Labels: ok-to-test

#173 Makefile - build binary when go.mod changes
  Makefile
Labels: ok-to-test

#175 Bumping up kube-burner to v1.13.0
  .github/workflows/builders.yml
  .github/workflows/gorelease.yml
  .github/workflows/linters.yml
  go.mod
  go.sum
Labels: ok-to-test

#170 [DNM] [rds-core] Add VFs to best effort pods
  cmd/config/rds-core/deployment-server.yml
Labels: enhancement

#174 add netpols to udn workload
  cmd/config/udn-density-pods/np-allow-from-clients.yml
  cmd/config/udn-density-pods/np-deny-all.yml
  cmd/config/udn-density-pods/udn-density-pods.yml
Labels: ok-to-test

#182 Add the required label to primary UDN namespaces
  cmd/config/udn-density-pods/udn-density-pods.yml
Labels: ok-to-test

#181 Increase vmi-ready-threshold timeout
  virt-density.go
Labels: ok-to-test
